### ISSUE TITLE
Visual Settings for the graph

### ISSUE THREAD

**Issue by AeyKeyZS** [microsoft/PowerBI-visuals-ForceGraph#47]
Can anyone please tell me how can I fix the position of a node or two.
Like: Node named "Start" at the top of the view
        Node named "End" at the bottom of the screen
Rest of the node in the centre space

And what is the meaning of these configurations:

private static ImagePosition: number = -12;
    private static MinNodeWeight: number = 5;
    private static MinCharge: number = -100;
    private static MaxCharge: number = -0.1;
    private static MinDecimalPlaces: number = 0;
    private static MaxDecimalPlaces: number = 5;
    private static GravityFactor: number = 100;
    private static LinkDistance: number = 200;
    private static HoverOpacity: number = 0.3;
    private static DefaultOpacity: number = 1;
    private static DefaultLinkColor: string = "#bbb";
    private static DefaultLinkHighlightColor: string = "#f00";
    private static DefaultLinkThickness: string = "1.5px";
    private static LabelsFontFamily: string = "sans-serif";
    private static MinRangeValue: number = 1;
    private static MaxRangeValue: number = 10;
    private static DefaultValueOfExistingLink: number = 1;
    private static DefaultLinkType: string = "";
    private static MinWeight: number = 0;
    private static MaxWeight: number = 0;
    private static DefaultSourceType: string = "";
    private static DefaultTargetType: string = "";
    private static StartOffset: string = "10%";
    private static DefaultLinkFillColor: string = "#000";
    private static LinkTextAnchor: string = "middle";
    private static DefaultLabelX: number = 12;
    private static DefaultLabelDy: string = ".35em";
    private static DefaultLabelText: string = "";
    private static ResolutionFactor: number = 20;
    private static ResolutionFactorBoundByBox: number = 0.9;
    private static LinkSelector: ClassAndSelector = createClassAndSelector("link");
    private static LinkLabelHolderSelector: ClassAndSelector = createClassAndSelector("linklabelholder");
    private static LinkLabelSelector: ClassAndSelector = createClassAndSelector("linklabel");
    private static NodeSelector: ClassAndSelector = createClassAndSelector("node");
    private static NoAnimationLimit: number = 200;

**Comment by helen508light** [comment]
It is general properties for graph view component from d3.force.layout
As you can see from the code, for example ImagePosition applied for images related to the graph's nodes.

Params like GravityFactors or LinkDistance are typical params for d3.force.layout:
`        this.forceLayout
            .gravity(ForceGraph.GravityFactor * k)
            .links(this.data.links)
            .size([this.viewport.width, this.viewport.height])
            .linkDistance(ForceGraph.LinkDistance)
            .charge(this.settings.size.charge / k);`

**Comment by helen508light** [comment]
If you want to have concrete node on the top/buttom, due to d3.force.layout you should associate node's value with y scale and then apply smth like this.
Also u need do specify yScale as d3.scale
`
simulation.force('y', d3.forceX().y(function(d) {
  return yScale(d.value);
}))
`

**Comment by AeyKeyZS** [comment]
From where can I import the "simulation" object... I couldn't find it

**Comment by helen508light** [comment]
i mean smth like this:
 simulation = d3.forceSimulation(nodes)

https://github.com/d3/d3-force#simulation_force
