### ISSUE TITLE
Labels truncated to 10 characters

### ISSUE THREAD

**Issue by erapade** [Microsoft/PowerBI-visuals-ForceGraph#7]
The node labels are truncated to 10 characters. Obviously it cant be infinit number of characters, but please add the possibility to specify the maximum number of characters in the settings menu. 
I guess doing the same for the links label would be a logical thing to do

**Comment by bischtob** [comment]
I am having the same issue.

**Comment by zBritva** [comment]
Hello, @erapade , @bischtob 

Did you try to change a parameter "Max name length" in "Format" panel at "Nodes" section?

![image](https://cloud.githubusercontent.com/assets/10897951/26403472/17f7b4e4-4097-11e7-80ca-75f3b1fdcc9b.png)

**Comment by helen508light** [comment]
This issue is solving just by applying the options @zBritva had written about
